#Parte 2

**Exercício 1**

In [28]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix


In [29]:
df = pd.read_csv("SolarPrediction.csv")

In [30]:
limite = df['Radiation'].median()
df['Target'] = np.where(df['Radiation'] >= limite, 1, 0)

In [31]:
X = df.drop(columns=['Radiation', 'Target', 'Data', 'Time', 'TimeSunRise', 'TimeSunSet'])
y = df['Target']

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [33]:
import matplotlib.pyplot as plt
import seaborn as sns

models = {
    "Árvore de Decisão": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC(random_state=42)
}

for nome, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"\nModelo: {nome}")
    print("Acurácia:", accuracy_score(y_test, y_pred))
    cm = confusion_matrix(y_test, y_pred)
    print("Matriz de Confusão:\n", cm)


Modelo: Árvore de Decisão
Acurácia: 0.943911890679176
Matriz de Confusão:
 [[4671  278]
 [ 272 4585]]

Modelo: Random Forest
Acurácia: 0.945849479910259
Matriz de Confusão:
 [[4782  167]
 [ 364 4493]]

Modelo: SVM
Acurácia: 0.8447889047521925
Matriz de Confusão:
 [[4676  273]
 [1249 3608]]


**Exercício 2**

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [21]:
df = pd.read_csv("T1.csv")

In [24]:
X = df.drop(columns=['LV ActivePower (kW)', 'Date/Time'])
y = df['LV ActivePower (kW)']

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
models = {
    "Regressão Linear": LinearRegression(),
    "Árvore de Regressão": DecisionTreeRegressor(random_state=42),
    "Random Forest Regressor": RandomForestRegressor(random_state=42)
}

for nome, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)
    print(f"\nModelo: {nome}")
    print("RMSE:", rmse)
    print("R²:", r2)


Modelo: Regressão Linear
RMSE: 411.7100216966853
R²: 0.9006599245385882

Modelo: Árvore de Regressão
RMSE: 538.7903745745243
R²: 0.8298698576314649

Modelo: Random Forest Regressor
RMSE: 412.8221448557191
R²: 0.9001225190519474
